### ISSUE TITLE
Please update version of gem on rubygems.org

### ISSUE THREAD

**Issue by avokhmin** [seanbehan/videojs_rails#16]
https://rubygems.org/gems/videojs_rails

Current version:
```
videojs_rails 4.6.1
```

**Comment by ACPK** [comment]
@grzlus @ain @avokhmin  Any update on this?

**Comment by avokhmin** [comment]
https://rubygems.org/gems/videojs_rails
@ACPK `videojs_rails 4.6.1` :(

**Comment by seanbehan** [comment]
@grzlus Hi. I'll add you as a collaborator. What's your rubygems email?

**Comment by meleyal** [comment]
+1

**Comment by grzlus** [comment]
@seanbehan My email is grzegorz@piklus.pl

Spambots alredy have it so I can give it to you via comment

**Comment by seanbehan** [comment]
Do you have an account on Rubygems w/ that email? Rubygems says that email isn't found.

**Comment by grzlus** [comment]
Yes, I have with that email: https://rubygems.org/profiles/grzlus

<img width="435" alt="edit_profile___rubygems_org___your_community_gem_host" src="https://cloud.githubusercontent.com/assets/1580215/8511058/4f3f6b32-2306-11e5-9ecf-56b6c368405a.png">

**Comment by seanbehan** [comment]
Thanks. I must have typed it wrong. You should be an owner on rubygems.

**Comment by grzlus** [comment]
Thanks! Today affter work I'll upload new versions to RubyGems

**Comment by jswanner** [comment]
Would it be possible to have v4.11.4 pushed to RubyGems? Thanks.

**Comment by grzlus** [comment]
@jswanner This version is now in RubyGems
