### ISSUE TITLE
:controls => true renders meaningless

### ISSUE THREAD

**Issue by ain** [seanbehan/videojs_rails#20]
As by the usage example in the README, `controls => false|true` has absolutely no impact on controls.

Version used: `4.6.1`.

**Comment by grzlus** [comment]
Regarding to this docs, this should work: https://github.com/videojs/video.js/blob/stable/docs/guides/options.md

I'll check that.

**Comment by grzlus** [comment]
Currently this works fine. I'll soo upload new versions to RubyGems
