### ISSUE TITLE
No video showing

### ISSUE THREAD

**Issue by silvercrow27** [seanbehan/videojs_rails#22]
Hello. I have implemented the gem as you said. But when I tried to view one theirs no video that is showing just a sound. But it is working in full screen.

**Comment by silvercrow27** [comment]
Sorry for a late reply. By the way, yes I can view the video. Ok ill try what you just said . 

Cheers,

**Comment by silvercrow27** [comment]
I guess solved this by getting the video-js.swf file on the javascript directory.

**Comment by keferboeck** [comment]
As reference if anyone faces the same issue - after specifying the height the video was displayed: 

example: 

= videojs_rails sources: { mp4: "YOUR_PATH_TO_VIDEO.mp4" }, setup: "{}", controls: false, width:"100%", height:"50%"
