### ISSUE TITLE
<div class="video-js-box"> will distort some css rules

### ISSUE THREAD

**Issue by redbar0n** [seanbehan/videojs_rails#26]
I am having some problems with videojs_rails adding the <div class="video-js-box"> surrounding the video. That means that there isn't a one to one correspondance between what the old video tag would output:

```
<video id="video" class="video-js vjs-default-skin" controls preload="none" width="700" height="400" poster="" data-setup="{}">
  <source src="http://cdn.example.com/test.mp4" type="video/mp4" />
	    
	    
</video>
```

And what videojs_rails will output:

```
<div class="video-js-box">
  <video id="" class=" video-js vjs-default-skin" controls preload="auto" width="700" height="400" poster="" data-setup="{}">
    <source src="http://cdn.example.com/test.mp4" type='video/mp4' />
    <source src="" type='video/webm' />
    <source src="" type='video/ogg' />
  </video>
</div>
```

Which causes some css rules to not apply. If it were only my own css rules, I could just change them, but there are some computed css rules which are causing the problem. The rules that would try to center the big initial play button in the video frame.

**Comment by grzlus** [comment]
You're right. This `div` tag could be removed.

**Comment by redbar0n** [comment]
Yes. Unfortunately the user of videojs_rails can't remove it himself, since it is a part of the output generated in place of the old video tag.

**Comment by grzlus** [comment]
This change is now in master. Soon it will be too in ruby gems.

**Comment by redbar0n** [comment]
Great, thanks.
