### ISSUE TITLE
Not working with turbolinks

### ISSUE THREAD

**Issue by andrkrn** [seanbehan/videojs_rails#27]

**Comment by grzlus** [comment]
Maybe some more informations? This gem wasn't designed to work with turbolinks. You can check https://github.com/videojs/video.js/issues/1516 and use some code from there.

**Comment by andrkrn** [comment]
```
change = ->
    for player in document.getElementsByClassName 'video-js'
        video = videojs('example_video')

before_change = ->
    for player in document.getElementsByClassName 'video-js'
        video = videojs('example_video')
        video.dispose()

$(document).on('page:before-change', before_change)
$(document).on('page:change', change)
```

I use this to make videojs work with turbolinks

**Comment by grzlus** [comment]
Thanks! I'll put it in README

**Comment by philipgiuliani** [comment]
There is still one small issue with this. "page:before-change" doesn't gets executed when you press the back button on the browser :'(

**Comment by grzlus** [comment]
@philipgiuliani check `page:before-unload`

**Comment by philipgiuliani** [comment]
That worked, thanks!

**Comment by nsantiago2719** [comment]
`page:before-unload` and `page:change` wont work in turbolink 5.0 use `turbolinks:load` and `turbolinks:before-visit` instead.

**Comment by gauda** [comment]
Using `turbolinks:load` and `turbolinks:before-visit` works great for initial page loads. But when navigating by clicking the back button `turbolinks:load` is not fired so no video is initialized. My current workaround is to call `Turbolinks.clearCache()` at the end of `change` but of course it's not that optimal to dispose cached pages. Is anyone aware of a better solution?

**Comment by nsantiago2719** [comment]
@gauda nope not yet. But still looking for other solutions.

**Comment by nsantiago2719** [comment]
@gauda can you take a look to this solution.
```
coffee script
change = ->
  if $('video').length > 0
    $('video').each(->
      player = videojs(@)
    )
  else
   if $('.video-box-container').length > 0
     $('.video-box-container').each(->
       video_container = $(@)
       video_container.html "<video class='video-js vjs-big-play-centered' id='#{ video_container.data('id') }' controls='#{ video_container.data('controls') }' data-setup='#{ video_container.data('options-setup') }'>
                               <source src='#{ video_container.data('options-src') }' />
                               <p class='vjs-no-js'>Please enable your javascript to view this video</p>
                             </video>"
       videojs(video_container.data('id'))
     )

before_change = ->
  if $('video').length > 0
    alert('visit initiated')
    $('video').each(->
      videojs(@).dispose()
      alert('videojs disposed')
    )
$(document).on("turbolinks:before-cache", before_change)
$(document).on("turbolinks:load", change)

HAML
.video-box-container{ data: { id: player_id, controls: :true, options: { setup: "", src: video.record_file.url } } }
  %video.video-js.vjs-big-play-centered{ id: player_id, controls: :true, data: { setup: "{}", src: video.record_file.url } }
    %source{ src: video.record_file.url }
    %p.vjs-no-js
      Pls enable your javascript to view this video.
```

The reason why videojs doesn't load when `turbolinks:load` is because it creates another div inside the videojs player but that is supposed to be the video. Now what I did was everytime turbolinks caches the page I dispose all videojs and on load it detects if it have container for videos which contain some information to rebuild the whole video tag to be initialized again in videojs. Not sure if this is the best way but for me it works.

**Comment by gauda** [comment]
Hey, great investigation. Nevertheless, my videos are way to dynamic for this solution (some have posters, multiple sources etc..)

**Comment by iraszl** [comment]
> ```
> change = ->
>     for player in document.getElementsByClassName 'video-js'
>         video = videojs('example_video')
> 
> before_change = ->
>     for player in document.getElementsByClassName 'video-js'
>         video = videojs('example_video')
>         video.dispose()
> 
> $(document).on('page:before-change', before_change)
> $(document).on('page:change', change)
> ```
> 
> I use this to make videojs work with turbolinks

Where do you put this code please to make it work with Turbolinks? Can you provide the directory and the filename?

**Comment by iraszl** [comment]
@andrkrn Where do you put this code please to make it work with Turbolinks? Can you provide the directory and the filename?

> ```
> change = ->
>     for player in document.getElementsByClassName 'video-js'
>         video = videojs('example_video')
> 
> before_change = ->
>     for player in document.getElementsByClassName 'video-js'
>         video = videojs('example_video')
>         video.dispose()
> 
> $(document).on('page:before-change', before_change)
> $(document).on('page:change', change)
> ```
> 
> I use this to make videojs work with turbolinks

**Comment by nsantiago2719** [comment]
Remembering on what I did before was I created another file in assets/js directory and named it as video.js.cofee( this is where I  add those codes including other videojs global configurations and customizations) and include it to my application.js.

**Comment by iraszl** [comment]
@nsantiago2719 Thank you!
