### ISSUE TITLE
Type on styling?

### ISSUE THREAD

**Issue by chrism** [seanbehan/videojs_rails#32]
Hi,

I feel like this has a typo which is making some of my styling break

https://github.com/seanbehan/videojs_rails/blob/master/lib/videojs_rails/view_helpers.rb#L18

shouldn't it be

`options[:class] = [options[:class], "video-js vjs-default-skin"].join(' ')`

not

`options[:class] = [options[:class], "vide-js vjs-default-skin"].join(' ')`

(video-js not vide-js)

thanks

**Comment by ryderhicks** [comment]
Yes, this is causing issues for me as well.

**Comment by grzlus** [comment]
I'll make release today to RubyGems

**Comment by chrism** [comment]
Fantastic, thanks!

:+1:

**Comment by grzlus** [comment]
Typo was made before my whole upgrade. I don't have time to upgrade all versions today.
